hydra:
  output_subdir: null
  run:  
    dir: .

model_id: Qwen/Qwen2.5-VL-72B-Instruct-AWQ
model_short_name: qwen
dataset: FHM
task: inpredict
batch_size: 1
extra_data: True
strategy: topk
para:
  do_sample: True
top_k: 15
reference_name: pairs_coverage_0.2_reference_15