hydra:
  output_subdir: null
  run:  
    dir: .

prompt: 
model_id: Qwen/Qwen2.5-VL-72B-Instruct-AWQ
model_short_name: qwen
dataset: ToxiCN
task: experience
para: {}
batch_size: 1
threshold: 0.8
pairs_name: pairs_coverage_0.2
experience_name: coverage_0.2